### PR TITLE
Adding support to Subversion

### PR DESCRIPTION
**Pull request by julianohaze**
This pull requests includes the support for Subversion to the metricminer project using the SVNKit library.

### CODE REVIEW

**Comment by mauricioaniche** [comment]
hi juliano,

what is the difference between working repositorypath and workingcopypath? I am imagining the simple case. I will 'svn checkout' a project, and then, point its directory to metricminer.

also, i don't think we need the subversionconfig class. it is just 4 parameters. we can receive directly on subservionrepository class.

what do you think?

**Comment by julianohaze** [comment]
Maurício,

repositorypath is the url you use to connect to the repository, like https://subversion.assembla.com/svn/metricminertest/. Working copy path is the directory you download the sources when you do a checkout. It is the path you are going to make your modifications before you commit. Are you suggesting we create a directory called metricminer and  checkout the sources there?

I don't see any problem if we remove the SubversionConfig class.

**Comment by mauricioaniche** [comment]
Hi Juliano,

Hmm, I get it. We need the remote URL because SVN needs to get information from it all the time, right?

What if we just have this remote URL? And MM2 checks it in some temporary directory? Does that make sense?

Oh, we also need the factory methods, just like GitRepository has. .singleProject(), allProjects().

**Comment by julianohaze** [comment]
Great!

I will make the changes!

**Pull request merged**
